### ISSUE TITLE
GlibC update

### ISSUE THREAD

**Issue by 24unix** [fanboimsft/kissD#1]
Hi,

has anybody tried it?

I made a kiss b and kiss i in the glibc,

and now at it says is:
Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!

**Comment by fanboimsft** [comment]
You should use the chroot image provided in releases, if you want something with actual support you can use https://github.com/gkisslinux/grepo.
